FROM tor2/centos-source-congress-base:4.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)



COPY extend_start.sh /usr/local/bin/kolla_congress_extend_start
RUN chmod 755 /usr/local/bin/kolla_congress_extend_start




USER congress