FROM tor2/centos-source-ceph-base:4.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)






# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT ["/usr/bin/ceph-fuse"]
CMD []