FROM tor2/centos-source-designate-base:4.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)





# The bind9 package here is only to provide the rndc binary.

    
       
    

RUN yum -y install bind && yum clean all




USER designate